### Create short url
POST http://localhost:3001/shorten
Content-Type: application/json

{
  "originalUrl": "https://jsonplaceholder.typicode.com/",
  "expiresAt": "2025-01-10T15:50:00.000Z",
  "customAlias": "mycustomalias"
}

### Redirect to original url
GET http://localhost:3001/mycustomalias

### Get info about url
GET http://localhost:3001/info/mycustomalias

### Get analytics
GET http://localhost:3001/analytics/35127e

### Delete short url
DELETE http://localhost:3001/delete/mycustomalias

