### Create short url
POST http://localhost:3001/api/shorten
Content-Type: application/json

{
  "originalUrl": "https://jsonplaceholder.typicode.com/",
  "expiresAt": "2025-01-09T17:50:00.000Z"
}

### Redirect to original url
GET http://localhost:3001/api/c28cc1

### Get info about url
GET http://localhost:3001/api/info/c28cc1

### Get analytics
GET http://localhost:3001/api/analytics/c28cc1

### Delete short url
DELETE http://localhost:3001/api/delete/c28cc1

